### ISSUE TITLE
12-Nov-21 Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by JEFFKAY16** [Tumworobere/To-Do-List#4]
## 12-Nov-21 Peer-To-Peer Code Review

Hi Annah, excellent work implementing a clean codebase. Below are a few suggestions on how the codebase can be improved:

- It's good practice to remove browser default stylings by using the `*` and setting the `margin` and `padding` to zero. 
- You can also add the `box-sizing: border-box` property which tells the browser to account for any border and padding in the values you specify for an element's width and height.

**Comment by Tumworobere** [comment]
Thank @JEFFKAY16 and @gracekabaghe 

i have worked on the requested changes!
